# This file was automatically generated by bakefile.
#
# Any manual changes will be lost if it is regenerated,
# modify the source .bkl file instead if possible.

# You may define standard make variables such as CFLAGS or
# CXXFLAGS to affect the build. For example, you could use:
#
#      make CXXFLAGS=-g
#
# to build with debug information. The full list of variables
# that can be used by this makefile is:
# AR, CC, CFLAGS, CPPFLAGS, CXX, CXXFLAGS, LD, LDFLAGS, MAKE, RANLIB.

# You may also specify config=Debug|Release
# or their corresponding lower case variants on make command line to select
# the corresponding default flags values.
ifeq ($(config),debug)
override config := Debug
endif
ifeq ($(config),release)
override config := Release
endif
ifeq ($(config),Debug)
CPPFLAGS ?= -DDEBUG
CFLAGS ?= -g -O0
CXXFLAGS ?= -g -O0
LDFLAGS ?= -g
else ifeq ($(config),Release)
CPPFLAGS ?= -DNDEBUG
CFLAGS ?= -O2
CXXFLAGS ?= -O2
else ifneq (,$(config))
$(warning Unknown configuration "$(config)")
endif

# Use "make RANLIB=''" for platforms without ranlib.
RANLIB ?= ranlib

CC := cc
CXX := c++

# The directory for the build files, may be overridden on make command line.
builddir = .

all: $(builddir)/my-router

$(builddir)/my-router: $(builddir)/my-router_my-router.o $(builddir)/my-router_network_table.o $(builddir)/my-router_router.o $(builddir)/my-router_udp.o
	$(CXX) -o $@ $(LDFLAGS) $(builddir)/my-router_my-router.o $(builddir)/my-router_network_table.o $(builddir)/my-router_router.o $(builddir)/my-router_udp.o -pthread

$(builddir)/my-router_my-router.o: my-router.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread my-router.cpp

$(builddir)/my-router_network_table.o: network_table.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread network_table.cpp

$(builddir)/my-router_router.o: router.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread router.cpp

$(builddir)/my-router_udp.o: udp.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread udp.cpp

clean:
	rm -f *.o
	rm -f *.d
	rm -f $(builddir)/my-router

.PHONY: all clean

# Dependencies tracking:
-include *.d
